---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Магазин — это SPA приложение, которое не перезагружает страницу.
  - Корзина хранится в сессии браузера.
implicit:
  - Пользователь должен иметь возможность видеть сколько страниц, какая страница по номеру,возможность выбрать нужную страницу
  - Если сайт предназначен для русскоговорящих пользователей, то в первую очередь он должен отображаться на русском языке
  - При выборе языка ставить флажок или галочку, какой на данный момент язык
  - При выборе необходимого товара в каталоге подсвечивать галочкой
  - При выборе категории добавить пустое значение
  - Отображается не весь список товара. Для того чтобы увидить другу часть товара нужно перейти на следующую страницу
  - Сделать в фильтре отдельные категории: бренд, цвет, ткань, размер и т.д
  - В форме Цена разделить от и до
  - В Форме Цена до, указывать придел не обязательно
  - При просмотре товара добавить возможность выбора цвета, размера, характеристика и т.д.
  - При добавлении товара в корзину, предоставить возможность указать необходимого количество выброного товара
  - При удалении товара из корзины или нажатии "очистить корзину", добавить уведомление с подтверждением удаления (очистить)
  - На страницу Корзины добавить кнопку "оформить заказ"
  - Регистрация клиента на сайте магазина
  - Вход в ЛК 
  - При заказе товара, клиент должен иметь возможность указать адрес доставки, 
  - Добавить информацию о компании
  - Контактные данные магазина для обратной связи
  - Информация по доставке, самовывоз
  - Информация об оплате
